spring:
  datasource-default:
    jdbc-url: jdbc:h2:mem:test1
    driver-class-name: org.h2.Driver
    username: root
    password: root

  datasource:
    jdbc-url: jdbc:h2:mem:test2
    driver-class-name: org.h2.Driver
    username: root
    password: root

  security:
    user:
      name: admin
      password: pass

management:
  endpoints:
    web:
      exposure:
        include: features
